# Generated by Django 3.0.2 on 2020-01-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True, verbose_name='question')),
                ('choice1', models.TextField(null=True, verbose_name='choice1')),
                ('choice2', models.TextField(null=True, verbose_name='choice1')),
                ('choice3', models.TextField(null=True, verbose_name='choice1')),
                ('choice4', models.TextField(null=True, verbose_name='choice1')),
                ('choice5', models.TextField(null=True, verbose_name='choice1')),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('created_date', models.DateField(auto_now=True)),
                ('url', models.URLField(null=True, verbose_name='url')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inception.Quiz'),
        ),
    ]
