# Generated by Django 3.0.2 on 2020-01-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0004_recommendresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(verbose_name='item')),
                ('price', models.TextField(verbose_name='price')),
                ('stock', models.TextField(verbose_name='stock')),
                ('store', models.TextField(verbose_name='store')),
                ('phone', models.TextField(verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='JoinList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(verbose_name='product')),
                ('price', models.TextField(verbose_name='price')),
                ('stock', models.TextField(verbose_name='stock')),
                ('store', models.TextField(verbose_name='store')),
                ('phone', models.TextField(verbose_name='phone')),
                ('result', models.TextField(verbose_name='result')),
            ],
        ),
    ]
