# Generated by Django 3.0.2 on 2020-01-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0005_itemlist_joinlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='itemName',
            field=models.TextField(default='name', verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemlist',
            name='storeName',
            field=models.TextField(default='name', verbose_name='store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinlist',
            name='itemName',
            field=models.TextField(default='name', verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinlist',
            name='storeName',
            field=models.TextField(default='name', verbose_name='store'),
            preserve_default=False,
        ),
    ]
