# Generated by Django 3.0.2 on 2020-01-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0006_auto_20200127_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendresult',
            name='time',
            field=models.TextField(default='time', verbose_name='result'),
            preserve_default=False,
        ),
    ]
