# Generated by Django 3.0.2 on 2020-01-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inception', '0007_recommendresult_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinlist',
            name='time',
            field=models.TextField(default='time', verbose_name='result'),
            preserve_default=False,
        ),
    ]
